default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: library_development